DROP SCHEMA IF EXISTS topology CASCADE;
DROP SCHEMA IF EXISTS tiger_data CASCADE;
DROP SCHEMA IF EXISTS tiger CASCADE;
DROP SCHEMA IF EXISTS private CASCADE; 

DROP TABLE IF EXISTS public.nowcast CASCADE;
DROP TABLE IF EXISTS public.forecast CASCADE; 
DROP TABLE IF EXISTS public.sensor_types CASCADE; 
DROP TABLE IF EXISTS public.shading CASCADE; 
DROP TABLE IF EXISTS public.radolan CASCADE; 
DROP TABLE IF EXISTS public.radolan_tiles CASCADE; 
DROP TABLE IF EXISTS public.weather CASCADE; 
DROP TABLE IF EXISTS public.weather_stations CASCADE; 
DROP TABLE IF EXISTS public.issues CASCADE; 
DROP TABLE IF EXISTS public.issue_types CASCADE; 
DROP TABLE IF EXISTS public.soil CASCADE; 
DROP TABLE IF EXISTS public.trees CASCADE; 

-- DROP EXTENSION postgis_topology CASCADE; 
--DROP EXTENSION postgis_tiger_geocoder CASCADE; 
DROP EXTENSION IF EXISTS fuzzystrmatch CASCADE;
DROP EXTENSION IF EXISTS postgis CASCADE;
