DROP MATERIALIZED VIEW public.watering; 
DROP MATERIALIZED VIEW public.vector_tiles; 
DROP MATERIALIZED VIEW public.expert_dashboard;
DROP VIEW private.nowcast_training_data;
DROP MATERIALIZED VIEW private.sensor_measurements_agg;
DROP MATERIALIZED VIEW public.rainfall; 
DROP MATERIALIZED VIEW public.radolan_14d_agg; 
DROP MATERIALIZED VIEW public.tree_radolan_tile; 
DROP MATERIALIZED VIEW private.weather_solaranywhere_14d_agg;
DROP MATERIALIZED VIEW public.weather_14d_agg; 